import type {
  BackendCommandName,
  BackendEventType,
  MockScenarioId,
} from './generated/backend-v1_2';

export const BACKEND_COMMAND_NAMES = [
  'getCapabilities',
  'getSnapshot',
  'createProject',
  'openProject',
  'closeProject',
  'importSources',
  'selectSourceDocument',
  'configureProvider',
  'startPipeline',
  'pausePipeline',
  'resumePipeline',
  'cancelPipeline',
  'retryFailedStage',
  'recoverFromCheckpoint',
  'exportOutputs',
  'resolveAsset',
  'readArtifact',
  'renderArtifactPage',
  'openArtifact',
  'revealArtifact',
  'getArtifactPath',
  'openOutputFolder',
  'revealLogFile',
  'acknowledgeWarning',
  'createWebAssistPackage',
  'listWebAssistPackages',
  'getWebAssistPackage',
  'validateWebAssistImport',
  'previewWebAssistDiff',
  'applyWebAssistImport',
  'discardWebAssistPackage',
  'openWebAssistPackageFolder',
  'undoWebAssistApply',
  'testProviderConnection',
] as const satisfies readonly BackendCommandName[];

export const DIRECT_COMMANDS = [
  'getCapabilities',
  'getSnapshot',
  'createProject',
  'openProject',
  'closeProject',
  'importSources',
  'selectSourceDocument',
  'configureProvider',
  'startPipeline',
  'pausePipeline',
  'resumePipeline',
  'cancelPipeline',
  'retryFailedStage',
  'recoverFromCheckpoint',
  'exportOutputs',
  'resolveAsset',
  'readArtifact',
  'renderArtifactPage',
  'openArtifact',
  'revealArtifact',
  'getArtifactPath',
  'openOutputFolder',
  'revealLogFile',
  'acknowledgeWarning',
  'createWebAssistPackage',
  'listWebAssistPackages',
  'getWebAssistPackage',
  'validateWebAssistImport',
  'previewWebAssistDiff',
  'applyWebAssistImport',
  'discardWebAssistPackage',
  'undoWebAssistApply',
  'testProviderConnection',
] as const satisfies readonly BackendCommandName[];

export const ADAPTER_COMMANDS = [
] as const satisfies readonly BackendCommandName[];

export const TRANSPORT_DEFERRED_COMMANDS = [
  'openWebAssistPackageFolder',
] as const satisfies readonly BackendCommandName[];

export const BACKEND_EVENT_TYPES = [
  'snapshot.updated',
  'project.loaded',
  'project.closed',
  'import.started',
  'import.progress',
  'import.completed',
  'import.failed',
  'pipeline.queued',
  'pipeline.stage_started',
  'pipeline.progress',
  'pipeline.stage_completed',
  'pipeline.paused',
  'pipeline.resumed',
  'pipeline.recovering',
  'pipeline.completed',
  'pipeline.warning',
  'pipeline.failed',
  'pipeline.cancelled',
  'export.started',
  'export.completed',
  'export.failed',
  'log.appended',
  'capabilities.changed',
  'backend.disconnected',
  'backend.reconnected',
  'web_assist.export_started',
  'web_assist.export_progress',
  'web_assist.export_completed',
  'web_assist.export_failed',
  'web_assist.import_started',
  'web_assist.import_validated',
  'web_assist.import_conflict',
  'web_assist.import_completed',
  'web_assist.import_failed',
  'web_assist.diff_ready',
  'web_assist.corrections_applied',
  'web_assist.corrections_undone',
] as const satisfies readonly BackendEventType[];

export const SNAPSHOT_REFRESH_EVENT_TYPES = new Set<BackendEventType>([
  'snapshot.updated',
  'project.loaded',
  'project.closed',
  'import.completed',
  'import.failed',
  'pipeline.queued',
  'pipeline.stage_started',
  'pipeline.progress',
  'pipeline.stage_completed',
  'pipeline.paused',
  'pipeline.resumed',
  'pipeline.recovering',
  'pipeline.completed',
  'pipeline.warning',
  'pipeline.failed',
  'pipeline.cancelled',
  'export.completed',
  'export.failed',
  'capabilities.changed',
  'backend.reconnected',
  'web_assist.export_completed',
  'web_assist.export_failed',
  'web_assist.import_validated',
  'web_assist.import_conflict',
  'web_assist.import_completed',
  'web_assist.import_failed',
  'web_assist.corrections_applied',
  'web_assist.corrections_undone',
]);

export const MOCK_SCENARIO_IDS = [
  'backend_disconnected',
  'empty_project',
  'project_loading',
  'project_ready',
  'importing_single_file',
  'importing_folder',
  'partial_import_success',
  'batch_queued',
  'ocr_running',
  'structure_rebuilding',
  'translation_running',
  'exporting',
  'paused',
  'recovering',
  'warning',
  'failed',
  'completed',
  'cancelled',
  'schema_mismatch',
  'command_rejected',
] as const satisfies readonly MockScenarioId[];
