from __future__ import annotations

from typing import Protocol


class TranslationProvider(Protocol):
    def translate_batch(self, units: list[dict]) -> list[dict]: ...
    def health_check(self) -> dict: ...
    def estimate_request(self, units: list[dict]) -> dict: ...
    def normalize_response(self, response: dict) -> list[dict]: ...


class VisionProvider(Protocol):
    def analyze_page(self, page: dict) -> dict: ...
    def health_check(self) -> dict: ...
    def normalize_response(self, response: dict) -> dict: ...
